version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    assignees:
      - HyperGH
    reviewers:
      - HyperGH
    rebase-strategy: auto
    target-branch: main