services:

  sned:
    build:
        context: .
        dockerfile: Dockerfile
        args:
          postgres_version: ${POSTGRES_VERSION:-14}
    command: ["python3.11", "-O", "main.py"]
    restart: always