[tool.black]
line-length = 120
target-version = ["py311"]
include = ".*py$"

[tool.ruff]
exclude = ["examples", "docs", "build"]
select = ["E", "F", "I"]
ignore = ["F405", "F403", "E501"]
line-length = 120
target-version = "py311"

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true

[tool.poetry]
name = "snedbot"
version = "0.1.0" # I do not actually update this, lol
description = "Your friendly neighbourhood multi-purpose Discord bot."
authors = ["HyperGH <46067571+HyperGH@users.noreply.github.com>"]
license = "GNU GPL-v3"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
dateparser = "^1.1.8"
psutil = "^5.9.4"
Pillow = "^10.0.0"
asyncpg = "^0.28.0"
Levenshtein = "^0.21.1"
uvloop = {version = "==0.17.0", platform="linux"}
aiodns = "~=3.0"
Brotli = "~=1.0"
ciso8601 = "~=2.3"
kosu = {git = "https://github.com/HyperGH/kosu.git", branch="main"}
hikari-lightbulb = "~=2.3.3"
hikari-miru = "~=3.1.2"

[tool.poetry.dev-dependencies]
black = "^23.3"
isort = "^5.12.0"
nox = "==2023.4.22"
ruff = "==0.0.286"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
