[tool.black]
line-length = 120
target-version = ["py310"]
include = ".*py$"

[tool.ruff]
exclude = ["examples", "docs", "build"]
select = ["E", "F", "I"]
ignore = ["F405", "F403", "E501"]
line-length = 120
target-version = "py310"

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true

[tool.poetry]
name = "snedbot"
version = "0.1.0" # I do not actually update this, lol
description = "Your friendly neighbourhood multi-purpose Discord bot."
authors = ["HyperGH <46067571+HyperGH@users.noreply.github.com>"]
license = "GNU GPL-v3"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
dateparser = "^1.1.6"
psutil = "^5.9.4"
Pillow = "^9.5.0"
asyncpg = "^0.27.0"
Levenshtein = "^0.20.9"
uvloop = {version = "==0.17.0", platform="linux"}
aiodns = "~=3.0"
cchardet = "~=2.1"
Brotli = "~=1.0"
ciso8601 = "~=2.3"
kosu = {git = "https://github.com/HyperGH/kosu.git", branch="main"}
hikari-lightbulb = "==2.3.1"
hikari-miru = "~=3.0.2"

[tool.poetry.dev-dependencies]
black = "^23.1"
isort = "^5.12.0"
nox = "==2022.11.21"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
